#!/bin/bash
#PBS -N SG_MISAR_E15_S2
#PBS -q normal
#PBS -l select=1:ngpus=1:mem=880G
#PBS -l walltime=20:00:00
#PBS -o /home/users/nus/dmeng/scratch/spbench/xlhuang/SpatialGlue/PBS/SpatialGlue/log/SG_MISAR_E15_S2.o
#PBS -e /home/users/nus/dmeng/scratch/spbench/xlhuang/SpatialGlue/PBS/SpatialGlue/log/SG_MISAR_E15_S2.e


# 
Dataset= 'Dataset name'
Method ='Method name'
Section= 'which section name'
JOB_NAME="benchmark"

echo "PBS_JOBID: $PBS_JOBID" > /home/users/nus/dmeng/scratch/spbench/xlhuang/SpatialGlue/PBS/SpatialGlue/log/SG_gpu.info
echo "hostname: $(hostname)" >> /home/users/nus/dmeng/scratch/spbench/xlhuang/SpatialGlue/PBS/SpatialGlue/log/SG_gpu.info

echo "export PBS_JOBID=$PBS_JOBID" > /home/users/nus/dmeng/scratch/spbench/xlhuang/SpatialGlue/PBS/SpatialGlue/log/SG_ssh_node
echo "ssh $(hostname)" >> /home/users/nus/dmeng/scratch/spbench/xlhuang/SpatialGlue/PBS/SpatialGlue/log/SG_ssh_node

echo "rm *.e *.o *.info ssh_node delete_all" > /home/users/nus/dmeng/scratch/spbench/xlhuang/SpatialGlue/PBS/SpatialGlue/log/delete_all

chmod +x /home/users/nus/dmeng/scratch/spbench/xlhuang/SpatialGlue/PBS/SpatialGlue/log/SG_ssh_node
chmod +x /home/users/nus/dmeng/scratch/spbench/xlhuang/SpatialGlue/PBS/SpatialGlue/log/delete_all

source ~/.bashrc  # 确保加载conda初始化配置
conda activate SpaMosaic

start_time=$(date +%s)

cd $PBS_O_WORKDIR

echo "Job started at: $(date)" > /home/users/nus/dmeng/scratch/spbench/xlhuang/SpatialGlue/PBS/SpatialGlue/log/${JOB_NAME}_${Method}_${Dataset}_${Section}.log

python /home/users/nus/dmeng/scratch/spbench/xlhuang/SpatialGlue/main.py --data_type MISAR --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR_S2/E15/MISAR_E15_5-S2_RNA.h5ad --ATAC_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR_S2/E15/MISAR_E15_5-S2_ATAC.h5ad --save_path /home/users/nus/dmeng/scratch/spbench/xlhuang/SpatialGlue/Results/MISAR/E15/SpatialGlue_MISAR_E15_S2.h5ad

end_time=$(date +%s)
echo "Job ended at: $(date)" >> /home/users/nus/dmeng/scratch/spbench/xlhuang/SpatialGlue/PBS/SpatialGlue/log/${JOB_NAME}_${Method}_${Dataset}_${Section}.log

elapsed_time=$((end_time - start_time))
echo "Total run time: $((elapsed_time / 3600)) hours $(( (elapsed_time % 3600) / 60)) minutes $((elapsed_time % 60)) seconds" >> /home/users/nus/dmeng/scratch/spbench/xlhuang/SpatialGlue/PBS/SpatialGlue/log/${JOB_NAME}_${Method}_${Dataset}_${Section}.log

