##HLN
#python main_PRAGA.py --data_type 10x --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/HLN/A1/adata_RNA.h5ad --ADT_path /home/users/nus/dmeng/scratch/spbench/Datasets/HLN/A1/adata_ADT.h5ad --save_path ./Results_PRAGA/HLN/A1/PRAGA_HLN_A1.h5ad
#python main_PRAGA.py --data_type 10x --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/HLN/D1/adata_RNA.h5ad --ADT_path /home/users/nus/dmeng/scratch/spbench/Datasets/HLN/D1/adata_ADT.h5ad --save_path ./Results_PRAGA/HLN/D1/PRAGA_HLN_D1.h5ad
#
##HT
#python main_PRAGA.py --data_type 10x --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/HT/slice1/s1_adata_rna.h5ad --ADT_path /home/users/nus/dmeng/scratch/spbench/Datasets/HT/slice1/s1_adata_adt.h5ad --save_path ./Results_PRAGA/HT/slice1/PRAGA_HT_s1.h5ad
#python main_PRAGA.py --data_type 10x --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/HT/slice2/s2_adata_rna.h5ad --ADT_path /home/users/nus/dmeng/scratch/spbench/Datasets/HT/slice2/s2_adata_adt.h5ad --save_path ./Results_PRAGA/HT/slice2/PRAGA_HT_s2.h5ad
#python main_PRAGA.py --data_type 10x --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/HT/slice3/s3_adata_rna.h5ad --ADT_path /home/users/nus/dmeng/scratch/spbench/Datasets/HT/slice3/s3_adata_adt.h5ad --save_path ./Results_PRAGA/HT/slice3/PRAGA_HT_s3.h5ad
#
##MISAR
#python main_PRAGA.py --data_type MISAR --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR/E11/MISAR_E11_0-S1_RNA.h5ad --ATAC_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR/E11/MISAR_E11_0-S1_ATAC.h5ad --save_path ./Results_PRAGA/MISAR/E11/PRAGA_MISAR_E11.h5ad
#python main_PRAGA.py --data_type MISAR --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR/E13/MISAR_E13_5-S1_RNA.h5ad --ATAC_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR/E13/MISAR_E13_5-S1_ATAC.h5ad --save_path ./Results_PRAGA/MISAR/E13/PRAGA_MISAR_E13.h5ad
#python main_PRAGA.py --data_type MISAR --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR/E15/MISAR_E15_5-S1_RNA.h5ad --ATAC_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR/E15/MISAR_E15_5-S1_ATAC.h5ad --save_path ./Results_PRAGA/MISAR/E15/PRAGA_MISAR_E15.h5ad
#python main_PRAGA.py --data_type MISAR --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR/E18/MISAR_18_5_S1_RNA.h5ad --ATAC_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR/E18/MISAR_18_5_S1_ATAC.h5ad --save_path ./Results_PRAGA/MISAR/E18/PRAGA_MISAR_E18.h5ad
#
#python main_PRAGA.py --data_type MISAR --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR_S2/E11/MISAR_E11_0-S2_RNA.h5ad --ATAC_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR_S2/E11/MISAR_E11_0-S2_ATAC.h5ad --save_path ./Results_PRAGA/MISAR/E11/PRAGA_MISAR_E11_S2.h5ad
#python main_PRAGA.py --data_type MISAR --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR_S2/E13/MISAR_E13_5-S2_RNA.h5ad --ATAC_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR_S2/E13/MISAR_E13_5-S2_ATAC.h5ad --save_path ./Results_PRAGA/MISAR/E13/PRAGA_MISAR_E13_S2.h5ad
#python main_PRAGA.py --data_type MISAR --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR_S2/E15/MISAR_E15_5-S2_RNA.h5ad --ATAC_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR_S2/E15/MISAR_E15_5-S2_ATAC.h5ad --save_path ./Results_PRAGA/MISAR/E15/PRAGA_MISAR_E15_S2.h5ad
#python main_PRAGA.py --data_type MISAR --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR_S2/E18/MISAR_18_5_S2_RNA.h5ad --ATAC_path /home/users/nus/dmeng/scratch/spbench/Datasets/MISAR_S2/E18/MISAR_18_5_S2_ATAC.h5ad --save_path ./Results_PRAGA/MISAR/E18/PRAGA_MISAR_E18_S2.h5ad
#
##Mouse_Brain
#python main_PRAGA.py --data_type Spatial-epigenome-transcriptome --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_Brain/Dataset10_Mouse_Brain_H3K27me3/adata_RNA.h5ad --ATAC_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_Brain/Dataset10_Mouse_Brain_H3K27me3/adata_peaks_normalized.h5ad --save_path ./Results_PRAGA/Mouse_Brain/H3K27me3/PRAGA_MB_H3K27me3.h5ad
#python main_PRAGA.py --data_type Spatial-epigenome-transcriptome --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_Brain/Dataset7_Mouse_Brain_ATAC/adata_RNA.h5ad --ATAC_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_Brain/Dataset7_Mouse_Brain_ATAC/adata_peaks_normalized.h5ad --save_path ./Results_PRAGA/Mouse_Brain/ATAC/PRAGA_MB_ATAC.h5ad
#python main_PRAGA.py --data_type Spatial-epigenome-transcriptome --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_Brain/Dataset8_Mouse_Brain_H3K4me3/adata_RNA.h5ad --ATAC_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_Brain/Dataset8_Mouse_Brain_H3K4me3/adata_peaks_normalized.h5ad --save_path ./Results_PRAGA/Mouse_Brain/H3K4me3/PRAGA_MB_H3K4me3.h5ad
#python main_PRAGA.py --data_type Spatial-epigenome-transcriptome --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_Brain/Dataset9_Mouse_Brain_H3K27ac/adata_RNA.h5ad --ATAC_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_Brain/Dataset9_Mouse_Brain_H3K27ac/adata_peaks_normalized.h5ad --save_path ./Results_PRAGA/Mouse_Brain/H3K27ac/PRAGA_MB_H3K27ac.h5ad
#
##Mouse_slpeen
#python main_PRAGA.py --data_type SPOTS --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_slpeen/Dataset1_Mouse_Spleen1/adata_RNA.h5ad --ADT_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_slpeen/Dataset1_Mouse_Spleen1/adata_ADT.h5ad --save_path ./Results_PRAGA/Mouse_slpeen/slice1/PRAGA_MS_s1.h5ad
#python main_PRAGA.py --data_type SPOTS --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_slpeen/Dataset2_Mouse_Spleen2/adata_RNA.h5ad --ADT_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_slpeen/Dataset2_Mouse_Spleen2/adata_ADT.h5ad --save_path ./Results_PRAGA/Mouse_slpeen/slice2/PRAGA_MS_s2.h5ad
#
##Mouse_Thymus
python main_PRAGA.py --data_type Stereo-CITE-seq --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_Thymus/Dataset3_Mouse_Thymus1/adata_RNA.h5ad --ADT_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_Thymus/Dataset3_Mouse_Thymus1/adata_ADT.h5ad --save_path ./Results_PRAGA/Mouse_Thymus/slice1/PRAGA_MT_s1.h5ad
#python main_PRAGA.py --data_type Stereo-CITE-seq --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_Thymus/Dataset4_Mouse_Thymus2/adata_RNA.h5ad --ADT_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_Thymus/Dataset4_Mouse_Thymus2/adata_ADT.h5ad --save_path ./Results_PRAGA/Mouse_Thymus/slice2/PRAGA_MT_s2.h5ad
#python main_PRAGA.py --data_type Stereo-CITE-seq --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_Thymus/Dataset5_Mouse_Thymus3/adata_RNA.h5ad --ADT_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_Thymus/Dataset5_Mouse_Thymus3/adata_ADT.h5ad --save_path ./Results_PRAGA/Mouse_Thymus/slice3/PRAGA_MT_s3.h5ad
#python main_PRAGA.py --data_type Stereo-CITE-seq --RNA_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_Thymus/Dataset6_Mouse_Thymus4/adata_RNA.h5ad --ADT_path /home/users/nus/dmeng/scratch/spbench/Datasets/Mouse_Thymus/Dataset6_Mouse_Thymus4/adata_ADT.h5ad --save_path ./Results_PRAGA/Mouse_Thymus/slice4/PRAGA_MT_s4.h5ad